# Copyright (C) 2019  SuperGreenLab <towelie@supergreenlab.com>
# Author: Constantin Clauzel <constantin.clauzel@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

core_modules:

  - wifi
  - ble
  - kv
  - ota
  - httpd
  - stat_dump
  - time
  - mqtt
  - i2c

custom_modules:

i2c_devices:

keys:

  #
  # Core keys
  #
  - name: wifi_status
    caps_name: WIFI_STATUS
    integer: true
    ble:
      uuid: "{0xee,0x06,0x0e,0xb5,0x31,0xae,0x83,0xf0,0xda,0xcb,0x67,0x6d,0x1c,0xda,0x2f,0x37}"
      notify: true
    default_var: DISCONNECTED

  - name: wifi_ssid
    caps_name: WIFI_SSID
    string: true
    nvs:
      key: WSSID
    ble:
      first: true
      uuid: "{0x17,0xfe,0xc3,0xc1,0x6b,0xe1,0x15,0x54,0xa5,0x74,0x55,0x9c,0x81,0x69,0xa3,0x6c}"
      write: true
    http:
      write: true
    write_cb: true
    default: 

  - name: wifi_password
    caps_name: WIFI_PASSWORD
    string: true
    nvs:
      key: WPASS
    ble:
      uuid: "{0xb9,0x5d,0x53,0x82,0x6e,0xcc,0xa0,0xfe,0xf1,0xa6,0xfe,0x6c,0x10,0x0b,0xe4,0xf7}"
      write: true
      notify: true
      no_sync: true
    http:
      write: true
    write_cb: true
    default: ""

  - name: time
    caps_name: TIME
    integer: true
    nvs:
      key: TIME
    ble:
      uuid: "{0x9b,0x6a,0x3b,0xe2,0xaa,0xb4,0x33,0xaa,0x8a,0x4a,0x9e,0xe1,0x4f,0xee,0xf9,0x40}"
      write: true
      notify: true
    http:
      write: true
    write_cb: true
    default: 0
 
  - name: n_restarts
    caps_name: N_RESTARTS
    integer: true
    nvs:
      key: N_RESTARTS
    http:
      noop: true
    default_var: 0

  - name: ota_timestamp
    caps_name: OTA_TIMESTAMP
    integer: true
    nvs:
      key: OTA_TMSTP
    http:
      write: true
    default_var: OTA_BUILD_TIMESTAMP

  - name: ota_server_ip
    caps_name: OTA_SERVER_IP
    string: true
    nvs:
      key: OTA_SRV_IP
    http:
      write: true
    default_var: CONFIG_OTA_SERVER_IP

  - name: ota_server_hostname
    caps_name: OTA_SERVER_HOSTNAME
    string: true
    nvs:
      key: OTA_SRV_HN
    http:
      write: true
    default_var: CONFIG_OTA_SERVER_HOSTNAME

  - name: ota_server_port
    caps_name: OTA_SERVER_PORT
    string: true
    nvs:
      key: OTA_SRV_PRT
    http:
      write: true
    default_var: CONFIG_OTA_SERVER_PORT

  - name: ota_version_filename
    caps_name: OTA_VERSION_FILENAME
    string: true
    nvs:
      key: OTA_VR_FILE
    http:
      write: true
    default_var: CONFIG_OTA_VERSION_FILENAME

  - name: ota_filename
    caps_name: OTA_FILENAME
    string: true
    nvs:
      key: OTA_FILE
    http:
      write: true
    default_var: CONFIG_OTA_FILENAME

  - name: mqtt_broker_url
    caps_name: OTA
    string: true
    nvs:
      key: OTA_SRV_IP
    http:
      write: true
    default_var: CONFIG_BROKER_URL

  - name: broker_url
    caps_name: BROKER_URL
    string: true
    nvs:
      key: BRKR_URL
    http:
      write: true
    default_var: CONFIG_BROKER_URL

  - name: i2c_sda
    caps_name: I2C_SDA
    integer: true
    nvs:
      key: I2C_SDA
    http:
      write: true
    default_var: DEFAULT_I2C_SDA

  - name: i2c_scl
    caps_name: I2C_SCL
    integer: true
    nvs:
      key: I2C_SCL
    http:
      write: true
    default_var: DEFAULT_I2C_SCL

  #
  # Custom keys
  #

